#!/bin/bash
###############################################
# Script to rebuild nemo restarts

# To call: 
# rebuild_nemo <filebase>
# where <filebase> is the path to the files that
# need rebuilding, without the _XXXX.nc component
# e.g. $RUN_DIR/restarts/AMM7_19930101_restart_trc
# 
# Files are rebuilt into the same location as the split files
###############################################
# CALLS: rebuild_nemo.exe
source ../config.sh

file=$1
ndomain=`ls ${file}_????.nc | wc -l`
nam_rebuild=${nam_rebuild:-nam_rebuild_$$}
MEMORY="10Gb"

#Find out the maximum number of files that can be opened and increase if necessary)
nopen=$(ulimit -n)
if [[ $ndomain -gt $nopen ]] ; then
  nopen=$((ndomain+4))   # +2 failed !!!
fi
ulimit -n $nopen

cat > $nam_rebuild << EOC
&nam_rebuild
filebase='${file}'
ndomain=${ndomain}
EOC
echo "/" >> $nam_rebuild

${EXECUTABLE_DIR}/rebuild_nemo.exe $nam_rebuild
rm -f $nam_rebuild
